docker_build:
  build: .
  dockerfile: ./docker/Dockerfile
  container_name: docker_build
  working_dir: /var/www/html
  ports:
    - "80:80"
  volumes:
    - .:/var/www/html
    - ./docker/nginx_log:/var/log/nginx
    - ./docker/php-fpm/php-fpm.log:/var/log/php-fpm.log
    - ./docker/config/app.conf:/etc/nginx/conf.d/app.conf
  links:
    - mysql

mysql:
  image: mysql:5.7
  environment:
    MYSQL_ROOT_PASSWORD: password
  volumes:
    - /var/mysql/:/var/lib/mysql
  ports:
    - "33307:3306"
